- name: Load br_netfilter
  modprobe:
    name: br_netfilter

- name: Set sysctl params required by Kubernetes
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "net.ipv4.ip_forward", value: 1 }
    - { key: "net.bridge.bridge-nf-call-iptables", value: 1 }
    - { key: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
